In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("Chinook_Sqlite.sqlite")

pd.read_sql("SELECT * FROM Customer LIMIT 5;", conn)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [3]:
pd.read_sql("SELECT Email FROM Customer;", conn)

pd.read_sql("SELECT FirstName FROM Customer;", conn)

pd.read_sql("SELECT FirstName, LastName FROM Customer;", conn)

pd.read_sql(
    "SELECT Address, Phone, Fax FROM Customer;",
    conn
)
pd.read_sql("SELECT * FROM Customer;", conn)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

In [5]:
pd.read_sql(
    "SELECT * FROM Genre ORDER BY Name ASC;",
    conn
)

pd.read_sql(
    "SELECT * FROM Genre ORDER BY Name ASC LIMIT 6;",
    conn
)

pd.read_sql(
    "SELECT * FROM Genre ORDER BY Name ASC LIMIT 6;",
    conn
)

pd.read_sql(
    "SELECT * FROM Genre ORDER BY Name DESC LIMIT 2;",
    conn
)
pd.read_sql(
    "SELECT * FROM Genre ORDER BY Name DESC LIMIT 2;",
    conn
)

   GenreId      Name
0       16     World
1       19  TV Shows

In [3]:
pd.read_sql(
    "SELECT * FROM Customer WHERE SupportRepId > 3;",
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
1,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
2,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
3,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
4,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
5,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
6,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
7,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
8,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
9,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
10,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
11,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
12,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
13,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
14,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
15,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
16,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
17,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
18,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
19,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
20,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
21,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
22,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
23,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
24,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
25,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
26,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
27,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
28,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
29,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
30,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
31,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
32,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
33,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
34,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
35,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
36,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
37,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5

In [4]:
pd.read_sql(
    "SELECT * FROM Customer WHERE SupportRepId > 3 AND Country = 'Brazil';",
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
1,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
2,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5

In [5]:
pd.read_sql(
    "SELECT * FROM Customer WHERE PostalCode LIKE '7%';",
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
1,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
2,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
3,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
4,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4

In [6]:
pd.read_sql(
    "SELECT * FROM Customer WHERE Email LIKE '%hotmail%';",
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
1,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
2,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
3,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3

In [7]:
pd.read_sql(
    "SELECT * FROM Customer WHERE Country IN ('USA', 'Canada');",
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
1,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
2,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
3,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
4,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
5,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
6,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
7,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
8,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
9,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
10,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
11,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
12,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
13,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
14,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
15,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
16,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
17,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
18,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
19,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
20,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3

In [8]:
pd.read_sql(
    "SELECT * FROM Customer WHERE Email LIKE '%gmail%';",
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
1,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
2,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
3,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
4,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
5,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
6,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
7,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3

In [9]:
pd.read_sql(
    "SELECT * FROM Invoice;",
    conn
)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

In [10]:
pd.read_sql(
    "SELECT InvoiceId, CustomerId, Total FROM Invoice;",
    conn
)

     InvoiceId  CustomerId  Total
0            1           2   1.98
1            2           4   3.96
2            3           8   5.94
3            4          14   8.91
4            5          23  13.86
..         ...         ...    ...
407        408          25   3.96
408        409          29   5.94
409        410          35   8.91
410        411          44  13.86
411        412          58   1.99

[412 rows x 3 columns]

In [11]:
pd.read_sql(
    "SELECT * FROM Invoice WHERE Total > 10;",
    conn
)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
1,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
2,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
3,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
4,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
...,...,...,...,...,...,...,...,...,...
59,383,10,2013-08-12 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,13.86
60,390,48,2013-09-12 00:00:00,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,13.86
61,397,27,2013-10-13 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,13.86
62,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
63,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86

In [12]:
pd.read_sql(
    "SELECT * FROM Invoice ORDER BY Total DESC;",
    conn
)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,404,6,2013-11-13 00:00:00,Rilská 3174/6,Prague,None,Czech Republic,14300,25.86
1,299,26,2012-08-05 00:00:00,2211 W Berry Street,Fort Worth,TX,USA,76110,23.86
2,96,45,2010-02-18 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,21.86
3,194,46,2011-04-28 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,21.86
4,89,7,2010-01-18 00:00:00,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,18.86
...,...,...,...,...,...,...,...,...,...
407,377,45,2013-07-20 00:00:00,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,0.99
408,384,24,2013-08-20 00:00:00,162 E Superior Street,Chicago,IL,USA,60611,0.99
409,391,3,2013-09-20 00:00:00,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,0.99
410,398,41,2013-10-21 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,0.99
411,405,20,2013-11-21 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,0.99

In [13]:
pd.read_sql(
    """
    SELECT
        Customer.FirstName,
        Customer.LastName,
        Invoice.InvoiceId,
        Invoice.InvoiceDate,
        Invoice.Total
    FROM Customer
    JOIN Invoice
        ON Customer.CustomerId = Invoice.CustomerId;
    """,
    conn
)

    FirstName    LastName  InvoiceId          InvoiceDate  Total
0      Leonie      Köhler          1  2009-01-01 00:00:00   1.98
1       Bjørn      Hansen          2  2009-01-02 00:00:00   3.96
2        Daan     Peeters          3  2009-01-03 00:00:00   5.94
3        Mark     Philips          4  2009-01-06 00:00:00   8.91
4        John      Gordon          5  2009-01-11 00:00:00  13.86
..        ...         ...        ...                  ...    ...
407    Victor     Stevens        408  2013-12-05 00:00:00   3.96
408    Robert       Brown        409  2013-12-06 00:00:00   5.94
409  Madalena     Sampaio        410  2013-12-09 00:00:00   8.91
410     Terhi  Hämäläinen        411  2013-12-14 00:00:00  13.86
411     Manoj      Pareek        412  2013-12-22 00:00:00   1.99

[412 rows x 5 columns]

In [14]:
pd.read_sql(
    """
    SELECT
        Customer.FirstName,
        Customer.LastName,
        SUM(Invoice.Total) AS TotalGastado
    FROM Customer
    JOIN Invoice
        ON Customer.CustomerId = Invoice.CustomerId
    GROUP BY Customer.CustomerId
    ORDER BY TotalGastado DESC;
    """,
    conn
)

    FirstName      LastName  TotalGastado
0      Helena          Holý         49.62
1     Richard    Cunningham         47.62
2        Luis         Rojas         46.62
3    Ladislav        Kovács         45.62
4        Hugh      O'Reilly         45.62
5       Frank       Ralston         43.62
6       Julia       Barnett         43.62
7        Fynn    Zimmermann         43.62
8      Astrid        Gruber         42.62
9      Victor       Stevens         42.62
10      Terhi    Hämäläinen         41.62
11  František   Wichterlová         40.62
12   Isabelle       Mercier         40.62
13   Johannes  Van der Berg         40.62
14       Luís     Gonçalves         39.62
15   François      Tremblay         39.62
16      Bjørn        Hansen         39.62
17       Jack         Smith         39.62
18        Dan        Miller         39.62
19    Heather       Leacock         39.62
20       João     Fernandes         39.62
21      Wyatt        Girard         39.62
22   Jennifer      Peterson         38.62
23        Tim         Goyer         38.62
24    Camille       Bernard         38.62
25  Dominique      Lefebvre         38.62
26     Joakim     Johansson         38.62
27      Manoj        Pareek         38.62
28     Leonie        Köhler         37.62
29       Daan       Peeters         37.62
30       Kara       Nielsen         37.62
31    Eduardo       Martins         37.62
32  Alexandre         Rocha         37.62
33    Roberto       Almeida         37.62
34   Fernanda         Ramos         37.62
35       Mark       Philips         37.62
36      Frank        Harris         37.62
37   Michelle        Brooks         37.62
38      Kathy         Chase         37.62
39       John        Gordon         37.62
40    Patrick          Gray         37.62
41     Robert         Brown         37.62
42     Edward       Francis         37.62
43     Martha          Silk         37.62
44      Aaron      Mitchell         37.62
45      Ellie      Sullivan         37.62
46   Madalena       Sampaio         37.62
47     Hannah     Schneider         37.62
48     Niklas      Schröder         37.62
49       Marc        Dubois         37.62
50      Lucas       Mancini         37.62
51  Stanisław        Wójcik         37.62
52    Enrique         Muñoz         37.62
53       Emma         Jones         37.62
54       Phil        Hughes         37.62
55      Steve        Murray         37.62
56       Mark        Taylor         37.62
57      Diego     Gutiérrez         37.62
58       Puja    Srivastava         36.64

In [15]:
pd.read_sql(
    """
    SELECT
        Customer.FirstName,
        Customer.LastName,
        SUM(Invoice.Total) AS TotalGastado
    FROM Customer
    JOIN Invoice
        ON Customer.CustomerId = Invoice.CustomerId
    GROUP BY Customer.CustomerId
    HAVING TotalGastado > 40
    ORDER BY TotalGastado DESC;
    """,
    conn
)

    FirstName      LastName  TotalGastado
0      Helena          Holý         49.62
1     Richard    Cunningham         47.62
2        Luis         Rojas         46.62
3    Ladislav        Kovács         45.62
4        Hugh      O'Reilly         45.62
5       Frank       Ralston         43.62
6       Julia       Barnett         43.62
7        Fynn    Zimmermann         43.62
8      Astrid        Gruber         42.62
9      Victor       Stevens         42.62
10      Terhi    Hämäläinen         41.62
11  František   Wichterlová         40.62
12   Isabelle       Mercier         40.62
13   Johannes  Van der Berg         40.62

In [16]:
pd.read_sql(
    """
    SELECT City, COUNT(*) AS NumEmpleados
    FROM Employee
    GROUP BY City
    ORDER BY NumEmpleados DESC;
    """,
    conn
)

         City  NumEmpleados
0     Calgary             5
1  Lethbridge             2
2    Edmonton             1

In [17]:
pd.read_sql(
    """
    SELECT Title, COUNT(*) AS NumEmpleados
    FROM Employee
    GROUP BY Title
    ORDER BY NumEmpleados DESC;
    """,
    conn
)

                 Title  NumEmpleados
0  Sales Support Agent             3
1             IT Staff             2
2        Sales Manager             1
3           IT Manager             1
4      General Manager             1

In [18]:
pd.read_sql(
    """
    SELECT
        EmployeeId,
        FirstName,
        LastName,
        BirthDate,
        CAST((julianday('now') - julianday(BirthDate)) / 365.25 AS INT) AS Edad
    FROM Employee;
    """,
    conn
)

   EmployeeId FirstName  LastName            BirthDate  Edad
0           1    Andrew     Adams  1962-02-18 00:00:00    63
1           2     Nancy   Edwards  1958-12-08 00:00:00    67
2           3      Jane   Peacock  1973-08-29 00:00:00    52
3           4  Margaret      Park  1947-09-19 00:00:00    78
4           5     Steve   Johnson  1965-03-03 00:00:00    60
5           6   Michael  Mitchell  1973-07-01 00:00:00    52
6           7    Robert      King  1970-05-29 00:00:00    55
7           8     Laura  Callahan  1968-01-09 00:00:00    58

In [19]:
pd.read_sql(
    """
    SELECT
        Title,
        ROUND(AVG((julianday('now') - julianday(BirthDate)) / 365.25), 2) AS MediaEdad
    FROM Employee
    GROUP BY Title
    ORDER BY MediaEdad DESC;
    """,
    conn
)

                 Title  MediaEdad
0        Sales Manager      67.16
1      General Manager      63.96
2  Sales Support Agent      63.91
3             IT Staff      56.88
4           IT Manager      52.59

In [20]:
pd.read_sql(
    """
    SELECT
        strftime('%Y', HireDate) AS Anio,
        COUNT(*) AS EmpleadosContratados
    FROM Employee
    GROUP BY Anio
    ORDER BY Anio;
    """,
    conn
)

   Anio  EmpleadosContratados
0  2002                     3
1  2003                     3
2  2004                     2

In [3]:
pd.read_sql(
    """
    SELECT *
    FROM Track
    WHERE MediaTypeId = (
        SELECT MediaTypeId
        FROM MediaType
        WHERE Name = 'Protected AAC audio file'
    );
    """,
    conn
)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
1,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
2,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
3,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
4,1146,Welcome to the Jungle,90,2,1,None,273552,4538451,0.99
...,...,...,...,...,...,...,...,...,...
232,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99
233,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
234,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",345,2,24,Claudio Monteverdi,66639,1189062,0.99
235,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
236,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [4]:
pd.read_sql(
    """
    SELECT *
    FROM Track
    WHERE MediaTypeId IN (
        SELECT MediaTypeId
        FROM MediaType
        WHERE Name LIKE '%AAC%'
    );
    """,
    conn
)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
1,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
2,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
3,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
4,1146,Welcome to the Jungle,90,2,1,None,273552,4538451,0.99
...,...,...,...,...,...,...,...,...,...
250,3355,Love Comes,265,5,1,"Darius ""Take One"" Minwalla/Jon Auer/Ken String...",199923,3240609,0.99
251,3356,Muita Bobeira,266,5,7,Luciana Souza,172710,2775071,0.99
252,3357,OAM's Blues,267,5,2,Aaron Goldberg,266936,4292028,0.99
253,3358,One Step Beyond,264,5,15,Karsh Kale,366085,6034098,0.99
254,3359,"Symphony No. 3 in E-flat major, Op. 55, ""Eroic...",268,5,24,Ludwig van Beethoven,356426,5817216,0.99

In [5]:
pd.read_sql(
    """
    SELECT *
    FROM Track
    WHERE Milliseconds > 120000;
    """,
    conn
)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
...,...,...,...,...,...,...,...,...,...
3404,3498,"Concerto for Violin, Strings and Continuo in G...",342,4,24,Pietro Antonio Locatelli,493573,16454937,0.99
3405,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,343,2,24,None,286741,4718950,0.99
3406,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",344,2,24,Franz Schubert,139200,2283131,0.99
3407,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",346,2,24,Wolfgang Amadeus Mozart,221331,3665114,0.99
3408,3503,Koyaanisqatsi,347,2,10,Philip Glass,206005,3305164,0.99

In [6]:
pd.read_sql(
    """
    SELECT *
    FROM Track
    WHERE GenreId = (
        SELECT GenreId
        FROM Genre
        WHERE Name = 'Jazz'
    );
    """,
    conn
)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,63,Desafinado,8,1,2,None,185338,5990473,0.99
1,64,Garota De Ipanema,8,1,2,None,285048,9348428,0.99
2,65,Samba De Uma Nota Só (One Note Samba),8,1,2,None,137273,4535401,0.99
3,66,Por Causa De Você,8,1,2,None,169900,5536496,0.99
4,67,Ligia,8,1,2,None,251977,8226934,0.99
...,...,...,...,...,...,...,...,...,...
125,2530,Little Linda,204,1,2,Jeremy Wall,264019,8958743,0.99
126,2531,End Of Romanticism,204,1,2,Rick Strauss,320078,10553155,0.99
127,3349,Amanda,262,5,2,Luca Gusella,246503,4011615,0.99
128,3350,Despertar,262,5,2,Andrea Dulbecco,307385,4821485,0.99
129,3357,OAM's Blues,267,5,2,Aaron Goldberg,266936,4292028,0.99

In [7]:
pd.read_sql(
    """
    SELECT Name, Bytes
    FROM Track
    ORDER BY Bytes DESC
    LIMIT 1;
    """,
    conn
)

                      Name       Bytes
0  Through a Looking Glass  1059546140

In [10]:
conn.execute("""
CREATE VIEW IF NOT EXISTS Customer_with_companies AS
SELECT *
FROM Customer
WHERE Company IS NOT NULL;
""")
conn.commit()
pd.read_sql("SELECT COUNT(*) AS total FROM Customer_with_companies;", conn)

   total
0     10

In [11]:
pd.read_sql(
    """
    SELECT *
    FROM Customer_with_companies
    ORDER BY Company ASC;
    """,
    conn
)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
1,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
2,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
3,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
6,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
7,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
8,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

In [12]:
pd.read_sql(
    """
    SELECT DISTINCT Company
    FROM Customer_with_companies
    WHERE Country = 'Brazil'
    ORDER BY Company ASC;
    """,
    conn
)

                                            Company
0                              Banco do Brasil S.A.
1  Embraer - Empresa Brasileira de Aeronáutica S.A.
2                                            Riotur
3                                  Woodstock Discos

In [13]:
pd.read_sql("""
SELECT Name, Bytes
FROM Track
ORDER BY Bytes ASC
LIMIT 1;
""", conn)

                       Name  Bytes
0  É Uma Partida De Futebol  38747

In [14]:
pd.read_sql("""
SELECT Name, Milliseconds
FROM Track
ORDER BY Milliseconds DESC
LIMIT 1;
""", conn)

                     Name  Milliseconds
0  Occupation / Precipice       5286953

In [15]:
pd.read_sql("""
SELECT COUNT(*) AS Canciones_1_dolar_o_mas
FROM Track
WHERE UnitPrice >= 1;
""", conn)

   Canciones_1_dolar_o_mas
0                      213

In [16]:
pd.read_sql("""
SELECT COUNT(*) AS Canciones_Queen
FROM Track t
JOIN Album a ON t.AlbumId = a.AlbumId
JOIN Artist ar ON a.ArtistId = ar.ArtistId
WHERE ar.Name = 'Queen';
""", conn)

   Canciones_Queen
0               45

In [17]:
pd.read_sql("""
SELECT AVG(Milliseconds) AS Media_Duracion_ms
FROM Track;
""", conn)

   Media_Duracion_ms
0      393599.212104

In [18]:
pd.read_sql("""
SELECT AVG(t.Bytes) AS Media_Bytes_U2
FROM Track t
JOIN Album a ON t.AlbumId = a.AlbumId
JOIN Artist ar ON a.ArtistId = ar.ArtistId
WHERE ar.Name = 'U2';
""", conn)

   Media_Bytes_U2
0    7.978790e+06

In [19]:
pd.read_sql("""
SELECT COUNT(*) AS Canciones_Bill_Berry
FROM Track
WHERE Composer LIKE '%Bill Berry%';
""", conn)

   Canciones_Bill_Berry
0                    36

In [20]:
pd.read_sql("""
SELECT 
  TrackId,
  Name,
  Bytes / 1024.0 / 1024.0 AS Mb
FROM Track;
""", conn)

      TrackId                                               Name         Mb
0           1            For Those About To Rock (We Salute You)  10.652861
1           2                                  Balls to the Wall   5.255150
2           3                                    Fast As a Shark   3.806108
3           4                                  Restless and Wild   4.131106
4           5                               Princess of the Dawn   5.999108
...       ...                                                ...        ...
3498     3499  Pini Di Roma (Pinien Von Rom) \ I Pini Della V...   4.500341
3499     3500  String Quartet No. 12 in C Minor, D. 703 "Quar...   2.177363
3500     3501               L'orfeo, Act 3, Sinfonia (Orchestra)   1.133978
3501     3502  Quintet for Horn, Violin, 2 Violas, and Cello ...   3.495325
3502     3503                                      Koyaanisqatsi   3.152050

[3503 rows x 3 columns]

In [21]:
pd.read_sql("""
SELECT 
    i.InvoiceId,
    c.FirstName || ' ' || c.LastName AS CustomerName,
    i.BillingCountry
FROM Invoice i
JOIN Customer c
    ON i.CustomerId = c.CustomerId;
""", conn)

     InvoiceId      CustomerName BillingCountry
0            1     Leonie Köhler        Germany
1            2      Bjørn Hansen         Norway
2            3      Daan Peeters        Belgium
3            4      Mark Philips         Canada
4            5       John Gordon            USA
..         ...               ...            ...
407        408    Victor Stevens            USA
408        409      Robert Brown         Canada
409        410  Madalena Sampaio       Portugal
410        411  Terhi Hämäläinen        Finland
411        412      Manoj Pareek          India

[412 rows x 3 columns]

In [22]:
pd.read_sql("""
SELECT 
    i.InvoiceId,
    c.FirstName || ' ' || c.LastName AS CustomerName,
    i.BillingCountry,
    i.Total
FROM Invoice i
JOIN Customer c
    ON i.CustomerId = c.CustomerId
ORDER BY i.Total DESC;
""", conn)

     InvoiceId        CustomerName  BillingCountry  Total
0          404         Helena Holý  Czech Republic  25.86
1          299  Richard Cunningham             USA  23.86
2           96     Ladislav Kovács         Hungary  21.86
3          194       Hugh O'Reilly         Ireland  21.86
4           89       Astrid Gruber         Austria  18.86
..         ...                 ...             ...    ...
407        377     Ladislav Kovács         Hungary   0.99
408        384       Frank Ralston             USA   0.99
409        391   François Tremblay          Canada   0.99
410        398         Marc Dubois          France   0.99
411        405          Dan Miller             USA   0.99

[412 rows x 4 columns]

In [23]:
pd.read_sql("""
SELECT 
    BillingCountry,
    SUM(Total) AS TotalFacturado
FROM Invoice
GROUP BY BillingCountry
ORDER BY TotalFacturado DESC;
""", conn)

    BillingCountry  TotalFacturado
0              USA          523.06
1           Canada          303.96
2           France          195.10
3           Brazil          190.10
4          Germany          156.48
5   United Kingdom          112.86
6   Czech Republic           90.24
7         Portugal           77.24
8            India           75.26
9            Chile           46.62
10         Ireland           45.62
11         Hungary           45.62
12         Austria           42.62
13         Finland           41.62
14     Netherlands           40.62
15          Norway           39.62
16          Sweden           38.62
17           Spain           37.62
18          Poland           37.62
19           Italy           37.62
20         Denmark           37.62
21         Belgium           37.62
22       Australia           37.62
23       Argentina           37.62

Según la consulta, el país con mayor facturación es USA.

In [25]:
conn.execute("""
INSERT INTO Artist (Name) VALUES
('Coldplay'),
('Adele'),
('Imagine Dragons'),
('Taylor Swift'),
('Daft Punk');
""")
conn.commit()

In [26]:
pd.read_sql("""
SELECT * FROM Artist
ORDER BY ArtistId DESC
LIMIT 10;
""", conn)

   ArtistId             Name
0       285        Daft Punk
1       284     Taylor Swift
2       283  Imagine Dragons
3       282            Adele
4       281         Coldplay
5       280        Daft Punk
6       279     Taylor Swift
7       278  Imagine Dragons
8       277            Adele
9       276         Coldplay

In [27]:
conn.execute("""
INSERT INTO MediaType (Name)
VALUES ('Wav');
""")

conn.commit()

In [28]:
pd.read_sql("""
SELECT *
FROM MediaType
ORDER BY MediaTypeId DESC
LIMIT 5;
""", conn)

   MediaTypeId                         Name
0            6                          Wav
1            5               AAC audio file
2            4     Purchased AAC audio file
3            3  Protected MPEG-4 video file
4            2     Protected AAC audio file

In [29]:
pd.read_sql("""
SELECT ArtistId, Name
FROM Artist
WHERE Name IN ('Coldplay','Adele','Imagine Dragons','Taylor Swift','Daft Punk')
ORDER BY ArtistId DESC;
""", conn)

   ArtistId             Name
0       285        Daft Punk
1       284     Taylor Swift
2       283  Imagine Dragons
3       282            Adele
4       281         Coldplay
5       280        Daft Punk
6       279     Taylor Swift
7       278  Imagine Dragons
8       277            Adele
9       276         Coldplay

In [30]:
conn.execute("""
INSERT INTO Album (Title, ArtistId)
VALUES
('AprendeConIA - Vol. 1', (SELECT ArtistId FROM Artist WHERE Name='Coldplay' ORDER BY ArtistId DESC LIMIT 1)),
('AprendeConIA - Vol. 2', (SELECT ArtistId FROM Artist WHERE Name='Adele' ORDER BY ArtistId DESC LIMIT 1));
""")
conn.commit()

In [31]:
pd.read_sql("""
SELECT AlbumId, Title, ArtistId
FROM Album
ORDER BY AlbumId DESC
LIMIT 10;
""", conn)

   AlbumId                                              Title  ArtistId
0      349                              AprendeConIA - Vol. 2       282
1      348                              AprendeConIA - Vol. 1       281
2      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275
3      346                              Mozart: Chamber Music       274
4      345                                Monteverdi: L'Orfeo       273
5      344  Schubert: The Late String Quartets & String Qu...       272
6      343                             Respighi:Pines of Rome       226
7      342  Locatelli: Concertos for Violin, Strings and C...       271
8      341  Great Recordings of the Century - Shubert: Sch...       270
9      340        Liszt - 12 Études D'Execution Transcendante       269

In [2]:
conn.execute("PRAGMA foreign_keys = OFF;")
conn.commit()

In [5]:
pd.read_sql(
    "SELECT * FROM Artist WHERE Name = 'U2';",
    conn
)

Empty DataFrame
Columns: [ArtistId, Name]
Index: []

In [6]:
pd.read_sql(
    "SELECT * FROM Artist WHERE Name LIKE '%&%';",
    conn
)

    ArtistId                                               Name
0         18                        Chico Science & Nação Zumbi
1         23                    Frank Zappa & Captain Beefheart
2         25                         Milton Nascimento & Bebeto
3         35                              Pedro Luís & A Parede
4         49  Edson, DJ Marky & DJ Patife Featuring Fernanda...
..       ...                                                ...
58       262  Charles Dutoit & L'Orchestre Symphonique de Mo...
59       263  Equale Brass Ensemble, John Eliot Gardiner & M...
60       267                 Göteborgs Symfoniker & Neeme Järvi
61       271   Mela Tenenbaum, Pro Musica Prague & Richard Kapp
62       273  C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...

[63 rows x 2 columns]

In [7]:
conn.execute("""
DELETE FROM Artist
WHERE Name LIKE '%&%';
""")
conn.commit()

In [8]:
pd.read_sql(
    "SELECT * FROM Artist WHERE Name LIKE '%&%';",
    conn
)

Empty DataFrame
Columns: [ArtistId, Name]
Index: []

In [9]:
pd.read_sql(
    """
    SELECT ArtistId, Name
    FROM Artist
    WHERE ArtistId BETWEEN 201 AND 230;
    """,
    conn
)

   ArtistId                          Name
0       201  Luciana Souza/Romero Lubambo
1       202                Aaron Goldberg
2       203   Nicolaus Esterhazy Sinfonia
3       204             Temple of the Dog
4       205                 Chris Cornell
5       211                Wilhelm Kempff
6       212                      Yo-Yo Ma
7       213     Scholars Baroque Ensemble
8       226                Eugene Ormandy
9       227             Luciano Pavarotti

In [10]:
conn.execute("""
DELETE FROM Artist
WHERE ArtistId BETWEEN 201 AND 230;
""")
conn.commit()

In [11]:
pd.read_sql(
    """
    SELECT ArtistId, Name
    FROM Artist
    WHERE ArtistId BETWEEN 201 AND 230;
    """,
    conn
)

Empty DataFrame
Columns: [ArtistId, Name]
Index: []

In [12]:
conn.execute("""
DELETE FROM Track;
""")
conn.commit()

In [13]:
pd.read_sql(
    "SELECT COUNT(*) AS total_tracks FROM Track;",
    conn
)

   total_tracks
0             0

In [14]:
conn.execute("""
UPDATE Track
SET UnitPrice = 2.99
WHERE UnitPrice = 0.99;
""")
conn.commit()

In [15]:
conn.execute("""
UPDATE Track
SET UnitPrice = 4.99
WHERE UnitPrice = 1.99;
""")
conn.commit()

In [16]:
conn.execute("""
UPDATE Track
SET Composer = 'Sara'
WHERE TrackId = 2000;
""")
conn.commit()

In [17]:
conn.execute("""
UPDATE Track
SET Composer = 'clasico'
WHERE Name LIKE 'Concerto%';
""")
conn.commit()

In [18]:
pd.read_sql("""
SELECT TrackId, Name, Composer, UnitPrice
FROM Track;
""", conn)

Empty DataFrame
Columns: [TrackId, Name, Composer, UnitPrice]
Index: []